apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wasm-on-every-request
spec:
  template:
    spec:
      containers:
        - image: hong0331/knative-serving-wasm-single-request  #CONFIGUREME: Put your image name here
          ports:
            - containerPort: 8080

    