apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wasm-on-every-request
spec:
  template:
    spec:
      containers:
        - image: hong0331/final-test-1 #TODO: Put your image name here
          ports:
            - containerPort: 8080

    