apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wasm-on-every-request
spec:
  template:
    spec:
      containers:
        - image: hong0331/wasm-on-every-request
          ports:
            - containerPort: 8080

    